// Real content reviewed in the public staging app on September 17, 2026.
// Media stays separate from layout so video can be added later.
const tvStories = [
  {id:'dracula',title:'Dracula',genre:'Horror · Thriller',image:'assets/dracula.webp',alt:'Jonathan Harker holds a lantern outside Castle Dracula beneath a full moon',logline:'The Count is expecting you.',url:'https://com-picsart-tv-stage.picsart.site/#scene=e8s5gmsva9&mode=watch'},
  {id:'tidebreak',title:'Tidebreak: The Glass Atlas',genre:'Fantasy · Adventure',image:'assets/tidebreak-waking-the-glass.webp',alt:'Nera and Sol examine a glowing blue glass atlas in a salvage boat cabin',logline:'One drowned island, one stolen signal, and a chart worth more than treasure.',url:'https://com-picsart-tv-stage.picsart.site/#scene=gajafa9qkz&mode=watch&collection=stories&at=btavnuqs43'},
  {id:'face',title:'The Last Good Face',genre:'Thriller · Fantasy',image:'assets/last-good-face.webp',alt:'Nino and Maka in a warmly lit portrait-restoration shop in Tbilisi',logline:'Every lie leaves a mark where only repair can erase it.',url:'https://com-picsart-tv-stage.picsart.site/#scene=jabnr2y9c9&mode=watch&collection=stories&at=jabnr2y9c9'},
];
const tvBranches = [
  {title:'Eyes in the Fog',text:'Harker raised his lantern toward the woods as grey wolves emerged from the mist.',credit:'A continuation by @paper-lantern-510',prompt:'Harker lifts the lantern and the wolves step out of the trees',image:'assets/eyes-in-the-fog.webp',alt:'Harker lifts his lantern beside the castle, looking toward the fog',url:'https://com-picsart-tv-stage.picsart.site/#scene=2yyup95e6j&mode=watch'},
  {title:'Whispers in Leather',text:'A strange scratching rustle emanated from Jonathan Harker’s leather satchel, freezing him in apprehension before the great doors.',credit:'A continuation by @velvet-compass-939',prompt:'A sound comes from satchel',image:'assets/whispers-in-leather.webp',alt:'Harker looks down toward the leather satchel across his chest',url:'https://com-picsart-tv-stage.picsart.site/#scene=bf2g4nz6qw&mode=watch'},
  {title:'At the Gate',text:'Jonathan stepped forward and struck the iron knocker against the massive wooden door, awaiting an answer in the cold night.',credit:'A continuation by @paper-lantern-510',prompt:'He knocks on the door',image:'assets/at-the-gate.webp',alt:'Harker reaches toward the massive wooden castle door',url:'https://com-picsart-tv-stage.picsart.site/#scene=247254pe8g&mode=watch&collection=stories&at=247254pe8g'},
];
const tvScreens = [
  {label:'Story map',title:'Every path has a story.',description:'Different people. Different next scenes. Follow an existing path or find an open ending to make your own.',image:'assets/current-story-map.png',alt:'Dracula story map with 11 scenes, 4 open endings and 3 different continuations from The Castle Door'},
  {label:'Watch',title:'Watch. Then wonder what if.',description:'Enjoy Tidebreak, choose a scene, and explore where it could go next. You can watch without adding anything.',image:'assets/current-watch.png',alt:'Tidebreak watch screen with Nera and Sol holding a glowing atlas, alongside scenes and Create from here'},
  {label:'Create',title:'Find your next beginning.',description:'Join an existing studio or start a new project. Your picture or idea can become a whole new world.',image:'assets/live-studios.png',alt:'Picsart TV studio collection and New project action, captured September 16'},
];
